### PR TITLE
Added bindings for camera methods

### PR DESCRIPTION
**Pull request by coolteemf**
Added bindings for some methods of the BaseCamera object, based on the model of the already made "rotate" method binding.

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hello @coolteemf,

Thanks for this PR. Everything looks ok to me, except the setCameraType. Would it be possible to have something like symbolic name (Orthographic instead of 0/1) it could be nice. Maybe this can be done by adding something like
Camera.Orthographic = 0
Camera.Parallel = 1 in the BaseCamera python binding. 

DM.

**Comment by coolteemf** [comment]
Hello @damienmarchal 
I thought that pushing my commit would update the pull request but it seems not.
So I have pushed the commit with the changes, which is not what I wanted to do.
Can the PR be updated by this new commit ?
I'm still a bit new with git.

**Comment by jnbrunet** [comment]
Hey @coolteemf ,

Thank you for this PR, and sorry for the slow feedback. Did you succeed to push your change? Normally, you only have to push a new commit to your branch coolteemf:Binding_BaseCamera and it should update the PR automatically.

**Comment by coolteemf** [comment]
Hey @jnbrunet ,
Thanks you for the feedback
It is what I thought I had done but I must have done something wrong at some point.
Anyways, the changes are here now.

**Comment by jnbrunet** [comment]
Awesome, thank you François. I added a small formatting correction. Let's merge this.

**Pull request merged**
