### PR TITLE
FIX: missing debug postfix in SofaPython3 plugin

### PR DESCRIPTION
**Pull request by marques-bruno**

### CODE REVIEW

**Comment by jnbrunet** [comment]
Looks like the build is failing. Does not seems to be related to your PR, do you know what's going on?

```
Plugin/src/SofaPython3/Prefab.cpp:61:65: error: no match for ‘operator=’ (operand types are ‘DeprecatedAndRemoved’ and ‘sofa::core::objectmodel::ComponentState’)
     m_componentstate = sofa::core::objectmodel::ComponentState::Valid;
                                                                 ^~~~~
In file included from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/BaseContext.h:25:0,
                 from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/BaseObject.h:25,
                 from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Context.h:25,
                 from /opt/sofa/include/SofaFramework/sofa/simulation/Node.h:28,
                 from /opt/sofa/include/SofaSimulation/SofaSimulationGraph/DAGNode.h:26,
                 from Plugin/src/SofaPython3/Prefab.h:2,
                 from Plugin/src/SofaPython3/Prefab.cpp:1:
/opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note: candidate: constexpr DeprecatedAndRemoved& DeprecatedAndRemoved::operator=(const DeprecatedAndRemoved&)
 class DeprecatedAndRemoved {};
       ^~~~~~~~~~~~~~~~~~~~
/opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note:   no known conversion for argument 1 from ‘sofa::core::objectmodel::ComponentState’ to ‘const DeprecatedAndRemoved&’
/opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note: candidate: constexpr DeprecatedAndRemoved& DeprecatedAndRemoved::operator=(DeprecatedAndRemoved&&)
/opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note:   no known conversion for argument 1 from ‘sofa::core::objectmodel::ComponentState’ to ‘DeprecatedAndRemoved&&’
```

**Comment by marques-bruno** [comment]
> Looks like the build is failing. Does not seems to be related to your PR, do you know what's going on?
> 
> ```
> Plugin/src/SofaPython3/Prefab.cpp:61:65: error: no match for ‘operator=’ (operand types are ‘DeprecatedAndRemoved’ and ‘sofa::core::objectmodel::ComponentState’)
>      m_componentstate = sofa::core::objectmodel::ComponentState::Valid;
>                                                                  ^~~~~
> In file included from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/BaseContext.h:25:0,
>                  from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/BaseObject.h:25,
>                  from /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Context.h:25,
>                  from /opt/sofa/include/SofaFramework/sofa/simulation/Node.h:28,
>                  from /opt/sofa/include/SofaSimulation/SofaSimulationGraph/DAGNode.h:26,
>                  from Plugin/src/SofaPython3/Prefab.h:2,
>                  from Plugin/src/SofaPython3/Prefab.cpp:1:
> /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note: candidate: constexpr DeprecatedAndRemoved& DeprecatedAndRemoved::operator=(const DeprecatedAndRemoved&)
>  class DeprecatedAndRemoved {};
>        ^~~~~~~~~~~~~~~~~~~~
> /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note:   no known conversion for argument 1 from ‘sofa::core::objectmodel::ComponentState’ to ‘const DeprecatedAndRemoved&’
> /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note: candidate: constexpr DeprecatedAndRemoved& DeprecatedAndRemoved::operator=(DeprecatedAndRemoved&&)
> /opt/sofa/include/SofaFramework/sofa/core/objectmodel/Base.h:102:7: note:   no known conversion for argument 1 from ‘sofa::core::objectmodel::ComponentState’ to ‘DeprecatedAndRemoved&&’
> ```

Yes, I know, I'll fix it ASAP ;)

**Comment by marques-bruno** [comment]
@jnbrunet #38

**Comment by jnbrunet** [comment]
You will have to rebase your branch to sp3/master to get your #38 fix for the CI

**Comment by marques-bruno** [comment]
> You will have to rebase your branch to sp3/master to get your #38 fix for the CI

oh I thought master was automatically rebased on PRs

**Comment by jnbrunet** [comment]
> > You will have to rebase your branch to sp3/master to get your #38 fix for the CI
> 
> oh I thought master was automatically rebased on PRs

This should _in theory_ be a one line changes to the github workflow file ^^

**Pull request merged**
