### PR TITLE
[CMake] FIX pybind11 finding python (2)

### PR DESCRIPTION
**Pull request by guparan**
**TO BE SQUASHED**

I thought PYTHON_EXECUTABLE was enough but apparently it's not with pybind11 2.4.3

See error in https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/master/CI_CONFIG=ubuntu_clang-6,CI_PLUGINS=options,CI_TYPE=release/2758/consoleFull

### CODE REVIEW

**Comment by guparan** [comment]
Tested successfully on 
CentOS: https://ci.inria.fr/sofa-ci-dev/job/sofa-custom/1756/CI_CONFIG=centos_clang-5,CI_TYPE=release/consoleFull
Ubuntu: https://ci.inria.fr/sofa-ci-dev/job/sofa-custom/1756/CI_CONFIG=ubuntu_clang-6,CI_TYPE=release/consoleFull

**Comment by jnbrunet** [comment]
CI here is not happy :-(

**Comment by guparan** [comment]
`cannot find -lpython3.7m`
Why that? :sob:

**Comment by guparan** [comment]
With my latest commit, SOFA CI will fail
```
--- find_package(Python) ---
-- Found Python: /usr/bin/python3.7 (found suitable version "3.7.5", minimum required is "3.7") found components:  Interpreter Development 
--- find_package(Python) done ---
--- find_package(pybind11) ---
-- Found PythonInterp: /usr/bin/python3.7 (found suitable version "3.7.5", minimum required is "3.7") 
-- Found PythonLibs: /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
--- find_package(pybind11) done ---
```

**Comment by guparan** [comment]
We should be good now @jnbrunet :+1:

**Comment by jnbrunet** [comment]
Hey @guparan 

Looks like the tests are failing on MacOS  because numpy cannot be found. Numpy is installed as a requirement so this sounds like numpy as been installed on a python version different from the one used for the compilation. Does that rings a bell?

**Comment by guparan** [comment]
SOFA minimal binaries do not include SP3 anymore but the workflows are fetching an old (always the same) version of the binaries. Maybe this is the cause?
If yes, #157 should solve that.

**Comment by jnbrunet** [comment]
Hum here the tests are running using the SP3 built previously in the same workflow, not the one downloaded from SOFA.

Looking quickly over your workflow result:
1. SP3 cmake shows that python 3.9 is used for building, even tho we set up version 3.7 for the job....
2. SP3 test job is setting python to version 3.7, and is using this python version to download numpy  

I'm not sure why python 3.9 is used here for the build job... It wasn't before your changes apparently.

**Comment by guparan** [comment]
@jnbrunet I'm done here too! Debug logs could be removed but it can wait another PR. 
Let's merge, SOFA CI has been waiting this fix for too long!

**Review by jnbrunet — APPROVED** [review]
All good here, if you could just resolve the conflicts (I just merged #157) , I'll merge as soon as its done

**Comment by guparan** [comment]
Done 👌

**Pull request merged**
