### PR TITLE
Fix compilation with MSVC

### PR DESCRIPTION
**Pull request by fredroy**
- PrefabLink needed == and != operators
~~- SofaExporter module name has been changed to Exporter to avoid collision with SofaExporter when generated the .lib file. (and all other bindings module does not have Sofa in their names anyway)~~

### CODE REVIEW

**Comment by damienmarchal** [comment]
Thanks @fredroy for you PR.
I fully agree with the fix on the DataPrefabLink. 
I'm a bit un-ease with the one one renaming SofaExporter. To me the python library should have the same name as their sofa counterpart otherwise it the open-door to un-managed entropy :)

**Comment by fredroy** [comment]
Make sense for SofaExporter.
I will try to find a way to just change the output .lib created by Windows (and not the pyd)

**Comment by fredroy** [comment]
Should I split the PR (with the only the operators) ? It will make MSVC compile if SofaExporter is not activated

**Comment by damienmarchal** [comment]
Hi @fredroy,

Thanks for your feedback. About the SofaExporter. Cannot we move the .lib in a different directory ? One dedcated to old python3 compiled library ?

**Comment by fredroy** [comment]
> 
> 
> Hi @fredroy,
> 
> Thanks for your feedback. About the SofaExporter. Cannot we move the .lib in a different directory ? One dedcated to old python3 compiled library ?

Yeah thats what I am searching for. I will try to change the SP3_add_python_module macro and set the LIBRARY_OUTPUT_PATH  property.

**Pull request merged**
