### PR TITLE
[SofaGL] Start a Sofa.SofaGL Module

### PR DESCRIPTION
**Pull request by psomers3**
I have started the bindings for a Sofa.SofaGL module so that other visualization tools from python can be used (two examples are also added for this). I imagine I should change the naming of the file that I do this bindings in because I started by thinking I need to wrap the drawtool and realized later that I don't need to. I can change the names to whatever you all feel appropriate if this small addition is worth it.

### CODE REVIEW

**Comment by jnbrunet** [comment]
Hey @psomers3 

Thanks a lot for this PR. Not everyone take the time to bring back their patch to the community. It is very appreciated.

I will try to review it on Monday.

**Comment by psomers3** [comment]
Out of curiousity, why are Sofa.GL and Sofa.Type the only modules with a "."?

**Comment by jnbrunet** [comment]
> Out of curiousity, why are Sofa.GL and Sofa.Type the only modules with a "."?

Sofa.GL and Sofa.Type are the first two modules of the "[next generation](https://github.com/sofa-framework/sofa/issues/1527)" of SOFA.

You can also have a look [here](https://annuel2.framapad.org/p/sofang-v7) to get an idea of the remaining modules that should be (hopefully) created in the upcoming months.

**Comment by jnbrunet** [comment]
Hey @psomers3 , 

Your PR looks good, and would be ready to be merged.

Did you had something else to add here?

**Comment by psomers3** [comment]
I guess looking at it, it would be more proper to add a description for the functions to the docs file... I can do that in a little bit.

**Comment by jnbrunet** [comment]
All right, I'll change the status to WIP (work in progress). Simply replace this PR label to "status: to review" once you have finished adding commits.

**Comment by psomers3** [comment]
@jnbrunet I can't change the label since I'm not a contributor, but I've added my changes and think it's good to go.

**Pull request merged**
