### PR TITLE
Binding base camera

### PR DESCRIPTION
**Pull request by coolteemf**
Added more bindings for camera methods.
The binded methods convert between screen pixel coordinates and word 3D coordinates.
These point conversion method should be the most useful among the other point conversion methods (e.g viewport/screen...)

### CODE REVIEW

**Comment by jnbrunet** [comment]
Hey @coolteemf ,

Thanks for these additions!

Could you add the label "pr: to review " once you have finished adding commits to your PR?

**Comment by coolteemf** [comment]
Hello @jnbrunet
Will do !

**Comment by coolteemf** [comment]
@hugtalbot Sorry for the long delay ^^'
I've pretty much binded everything that I needed, I'm not sure if it is relevant to bind the rest.

**Comment by coolteemf** [comment]
@jnbrunet I'm sorry I don't see a button to add a label...

**Pull request merged**
