### PR TITLE
[bindings] Adds some bindings

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
Adds bindings:
- bwdInit()
- storeResetState()

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi @EulalieCoevoet,

Thank for the PR. 

In the sofa dev meeting it is often said that bwInit is something that was useful at xml time and probably to remove.
Do you have component in mind that couldn't be rewritten by removing the bwInit ?

**Comment by EulalieCoevoet** [comment]
Well I think it can be useful you need a node, or a component to be initialized before adding something else in the scene ?

In my case for instance. I have an articulated system and I want to initialize the system with non-zero value at the joints, so that the system is set to a configuration when I start the simulation. But now I also want to add something at the end effector that depends on the initialized position of this end effector. 

Now that I think about it, this is actually an old patch and I remember that I was expecting the bwdInit() to do the trick but instead had to use the storeResetState()...

**Comment by damienmarchal** [comment]
I'm curious to see if the behavior your expect, creating a component, then changing one of its datafield and having it properly initialized, cannot be implemented using the addUpdateCallback feature introduced some time ago. 
See: MeshLoader.cpp line 135

**Comment by EulalieCoevoet** [comment]
No as I said the one that I'm using is storeResetState(). I guess I'll wait for your changes and see if it fits my needs.

**Pull request closed without merging**
